platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../common/temp/node_modules/.pnpm/@capacitor+ios@3.5.1_@capacitor+core@3.5.1/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../common/temp/node_modules/.pnpm/@capacitor+ios@3.5.1_@capacitor+core@3.5.1/node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
