# Unique identifier of the github workflow.
name: CI

# Events used by GitHub to trigger workflow.
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    # Type of machine to run the job on.
    runs-on: ubuntu-latest

    # A job contains a sequence of steps.
    steps:
      # Fetch the repository.
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install default Node.js.
      - name: Environment
        uses: actions/setup-node@v3

      # Install the dependencies.
      - name: Dependencies
        run: node common/scripts/install-run-rush.js install

      # Build registered packages.
      - name: Build project
        run: node common/scripts/install-run-rush.js build

      # Test registered packages.
      - name: Testing project
        run: node common/scripts/install-run-rush.js test
